services:
  csskins_postgres:
    image: postgres:15
    container_name: csskins_postgres
    environment:
      POSTGRES_DB: cs_steam_marketplace
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
    ports:
      - "5432:5432"
    volumes:
      - csskins_postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U root -d cs_steam_marketplace"]
      interval: 5s
      retries: 5
      start_period: 10s
      timeout: 3s

  csskins_parser:
    build: ./parser
    container_name: parser_csskins
    environment:
      PARSER_MODE: update
      DB_NAME: cs_steam_marketplace
      DB_USER: root
      DB_PASSWORD: root
      DB_HOST: csskins_postgres
      DB_PORT: 5432
    volumes:
      - /csskins_proxie/proxies.txt:/app/proxies.txt
    depends_on:
      - csskins_postgres
    command: /app/wait-for-it.sh csskins_postgres:5432 -- python /app/main.py
volumes:
  csskins_postgres_data:
